/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author aldebaranbn
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        MenuUtama = new javax.swing.JPanel();
        SI = new javax.swing.JLabel();
        tambahRuangan = new javax.swing.JToggleButton();
        tambahDokter = new javax.swing.JToggleButton();
        tambahPasienInap = new javax.swing.JToggleButton();
        hapusDokter = new javax.swing.JToggleButton();
        hapusPasien = new javax.swing.JToggleButton();
        cariDokter = new javax.swing.JToggleButton();
        cariPasien = new javax.swing.JToggleButton();
        viewPasienInap = new javax.swing.JToggleButton();
        viewDokter = new javax.swing.JToggleButton();
        exit = new javax.swing.JToggleButton();
        MenuHapusDokter = new javax.swing.JPanel();
        delDokter = new javax.swing.JLabel();
        NIP = new javax.swing.JLabel();
        NIPField = new javax.swing.JTextField();
        btnHapusDokter = new javax.swing.JButton();
        btnTutupDokter = new javax.swing.JButton();
        MenuCariDokter = new javax.swing.JPanel();
        CariDokter = new javax.swing.JLabel();
        NIPCari = new javax.swing.JLabel();
        NIPCariField = new javax.swing.JTextField();
        btnCariDokter = new javax.swing.JButton();
        DokterDitemukan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        MenuCariPasienInap = new javax.swing.JPanel();
        CariPasien = new javax.swing.JLabel();
        NoRegCari = new javax.swing.JLabel();
        NoRegCariField = new javax.swing.JTextField();
        btnCariPasien = new javax.swing.JButton();
        PasienDitemukan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MenuHapusPasien = new javax.swing.JPanel();
        HapusPasien = new javax.swing.JLabel();
        NoRegHapus = new javax.swing.JLabel();
        NoRegHapusField = new javax.swing.JTextField();
        btnHapusPasien = new javax.swing.JButton();
        btnTutupPasien = new javax.swing.JButton();
        MenuTambahDokter = new javax.swing.JPanel();
        TambahDokter = new javax.swing.JLabel();
        NamaDokter = new javax.swing.JLabel();
        UmurDokter = new javax.swing.JLabel();
        JKDokter = new javax.swing.JLabel();
        AlamatDokter = new javax.swing.JLabel();
        Spesialis = new javax.swing.JLabel();
        NIPDokter = new javax.swing.JLabel();
        NamaDokterField = new javax.swing.JTextField();
        UmurDokterField = new javax.swing.JTextField();
        JKDokterField = new javax.swing.JTextField();
        AlamatDokterField = new javax.swing.JTextField();
        SpesialisField = new javax.swing.JTextField();
        NIPDokterField = new javax.swing.JTextField();
        simpanDokter = new javax.swing.JButton();
        tutupTambahDokter = new javax.swing.JButton();
        MenuTambahPasienInap = new javax.swing.JPanel();
        TambahPasien = new javax.swing.JLabel();
        NamaPasien = new javax.swing.JLabel();
        UmurPasien = new javax.swing.JLabel();
        AlamatPasien = new javax.swing.JLabel();
        JKPasien = new javax.swing.JLabel();
        NoReg = new javax.swing.JLabel();
        Diagnosa = new javax.swing.JLabel();
        NIPDokterPasien = new javax.swing.JLabel();
        namaPasienField = new javax.swing.JTextField();
        umurPasienField = new javax.swing.JTextField();
        alamatPasienField = new javax.swing.JTextField();
        JKPasienField = new javax.swing.JTextField();
        noRegField = new javax.swing.JTextField();
        diagnosaField = new javax.swing.JTextField();
        NIPDokterPasienField = new javax.swing.JTextField();
        btnSimpanPasien = new javax.swing.JButton();
        btnTutupTambahPasien = new javax.swing.JButton();
        MenuTambahRuangan = new javax.swing.JPanel();
        TambahRuangan = new javax.swing.JLabel();
        NoRuangan = new javax.swing.JLabel();
        NoRuanganField = new javax.swing.JTextField();
        btnSimpanRuangan = new javax.swing.JButton();
        btnTutupTambahRuangan = new javax.swing.JButton();
        MenuViewDaftarDokter = new javax.swing.JPanel();
        DaftarDokter = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        MenuViewDaftarPasienInap = new javax.swing.JPanel();
        DaftarPasien = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new java.awt.CardLayout());

        SI.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        SI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SI.setText("Sistem Informasi Pasien Rawat Inap");

        tambahRuangan.setText("Tambah Ruangan");
        tambahRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahRuanganActionPerformed(evt);
            }
        });

        tambahDokter.setText("Tambah Dokter");

        tambahPasienInap.setText("Tambah Pasien Inap");

        hapusDokter.setText("Hapus Dokter");
        hapusDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDokterActionPerformed(evt);
            }
        });

        hapusPasien.setText("Hapus Pasien");
        hapusPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPasienActionPerformed(evt);
            }
        });

        cariDokter.setText("Cari Dokter");

        cariPasien.setText("Cari Pasien");
        cariPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPasienActionPerformed(evt);
            }
        });

        viewPasienInap.setText("Tampilkan Data Pasien Inap");

        viewDokter.setText("Tampilkan Data Dokter");

        exit.setText("Keluar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuUtamaLayout = new javax.swing.GroupLayout(MenuUtama);
        MenuUtama.setLayout(MenuUtamaLayout);
        MenuUtamaLayout.setHorizontalGroup(
            MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuUtamaLayout.createSequentialGroup()
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(SI, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuUtamaLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(tambahPasienInap, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hapusPasien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariPasien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewPasienInap, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60)
                        .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hapusDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(exit))
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(tambahRuangan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuUtamaLayout.setVerticalGroup(
            MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(tambahRuangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahPasienInap)
                    .addComponent(tambahDokter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusPasien)
                    .addComponent(hapusDokter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariPasien)
                    .addComponent(cariDokter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPasienInap)
                    .addComponent(viewDokter))
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuUtama, "card2");

        delDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        delDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delDokter.setText("Hapus Dokter");

        NIP.setText("Masukkan NIP Dokter");

        btnHapusDokter.setText("Hapus");

        btnTutupDokter.setText("Tutup");

        javax.swing.GroupLayout MenuHapusDokterLayout = new javax.swing.GroupLayout(MenuHapusDokter);
        MenuHapusDokter.setLayout(MenuHapusDokterLayout);
        MenuHapusDokterLayout.setHorizontalGroup(
            MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                .addGroup(MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NIP)
                        .addGap(18, 18, 18)
                        .addComponent(NIPField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnHapusDokter)
                        .addGap(55, 55, 55)
                        .addComponent(btnTutupDokter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHapusDokterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(delDokter)
                .addGap(88, 88, 88))
        );
        MenuHapusDokterLayout.setVerticalGroup(
            MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delDokter)
                .addGap(18, 18, 18)
                .addGroup(MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIP)
                    .addComponent(NIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusDokter)
                    .addComponent(btnTutupDokter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuHapusDokter, "card3");

        CariDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CariDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CariDokter.setText("Cari Dokter");

        NIPCari.setText("Masukkan NIP Dokter");

        btnCariDokter.setText("Cari");

        DokterDitemukan.setText("Data Dokter");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout MenuCariDokterLayout = new javax.swing.GroupLayout(MenuCariDokter);
        MenuCariDokter.setLayout(MenuCariDokterLayout);
        MenuCariDokterLayout.setHorizontalGroup(
            MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariDokterLayout.createSequentialGroup()
                .addGroup(MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCariDokterLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DokterDitemukan)
                            .addGroup(MenuCariDokterLayout.createSequentialGroup()
                                .addComponent(NIPCari)
                                .addGap(18, 18, 18)
                                .addComponent(NIPCariField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnCariDokter))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuCariDokterLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(CariDokter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuCariDokterLayout.setVerticalGroup(
            MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CariDokter)
                .addGap(18, 18, 18)
                .addGroup(MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIPCari)
                    .addComponent(NIPCariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariDokter))
                .addGap(27, 27, 27)
                .addComponent(DokterDitemukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuCariDokter, "card4");

        CariPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CariPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CariPasien.setText("Cari Pasien Inap");

        NoRegCari.setText("Masukkan No. Registrasi Pasien");

        btnCariPasien.setText("Cari");

        PasienDitemukan.setText("Data Pasien Inap");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout MenuCariPasienInapLayout = new javax.swing.GroupLayout(MenuCariPasienInap);
        MenuCariPasienInap.setLayout(MenuCariPasienInapLayout);
        MenuCariPasienInapLayout.setHorizontalGroup(
            MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCariPasienInapLayout.createSequentialGroup()
                        .addComponent(NoRegCari)
                        .addGap(18, 18, 18)
                        .addComponent(NoRegCariField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariPasien))
                    .addComponent(PasienDitemukan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuCariPasienInapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CariPasien)
                .addGap(153, 153, 153))
        );
        MenuCariPasienInapLayout.setVerticalGroup(
            MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CariPasien)
                .addGap(18, 18, 18)
                .addGroup(MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoRegCari)
                    .addComponent(NoRegCariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPasien))
                .addGap(18, 18, 18)
                .addComponent(PasienDitemukan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Panel.add(MenuCariPasienInap, "card5");

        HapusPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        HapusPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HapusPasien.setText("Hapus Pasien Inap");

        NoRegHapus.setText("Masukkan No. Registrasi pasien");

        NoRegHapusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRegHapusFieldActionPerformed(evt);
            }
        });

        btnHapusPasien.setText("Hapus");
        btnHapusPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPasienActionPerformed(evt);
            }
        });

        btnTutupPasien.setText("Tutup");
        btnTutupPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupPasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuHapusPasienLayout = new javax.swing.GroupLayout(MenuHapusPasien);
        MenuHapusPasien.setLayout(MenuHapusPasienLayout);
        MenuHapusPasienLayout.setHorizontalGroup(
            MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(HapusPasien))
                    .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapusPasien)
                            .addComponent(NoRegHapus))
                        .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NoRegHapusField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnTutupPasien)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        MenuHapusPasienLayout.setVerticalGroup(
            MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HapusPasien)
                .addGap(18, 18, 18)
                .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoRegHapus)
                    .addComponent(NoRegHapusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusPasien)
                    .addComponent(btnTutupPasien))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Panel.add(MenuHapusPasien, "card6");

        TambahDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TambahDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahDokter.setText("Tambah Dokter");

        NamaDokter.setText("Nama");

        UmurDokter.setText("Umur");

        JKDokter.setText("Jenis kelamin");

        AlamatDokter.setText("Alamat");

        Spesialis.setText("Bidang spesialis");

        NIPDokter.setText("NIP");

        NamaDokterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaDokterFieldActionPerformed(evt);
            }
        });

        NIPDokterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIPDokterFieldActionPerformed(evt);
            }
        });

        simpanDokter.setText("Simpan");

        tutupTambahDokter.setText("Tutup");

        javax.swing.GroupLayout MenuTambahDokterLayout = new javax.swing.GroupLayout(MenuTambahDokter);
        MenuTambahDokter.setLayout(MenuTambahDokterLayout);
        MenuTambahDokterLayout.setHorizontalGroup(
            MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UmurDokter)
                            .addComponent(NamaDokter))
                        .addGap(69, 69, 69)
                        .addComponent(NamaDokterField, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(UmurDokterField))
                            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JKDokter)
                                    .addComponent(AlamatDokter)
                                    .addComponent(Spesialis)
                                    .addComponent(NIPDokter))
                                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JKDokterField)
                                            .addComponent(AlamatDokterField)))
                                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SpesialisField)
                                            .addComponent(NIPDokterField))))))))
                .addGap(29, 29, 29))
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(TambahDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpanDokter)
                .addGap(72, 72, 72)
                .addComponent(tutupTambahDokter)
                .addGap(165, 165, 165))
        );
        MenuTambahDokterLayout.setVerticalGroup(
            MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TambahDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaDokter)
                    .addComponent(NamaDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UmurDokter)
                    .addComponent(UmurDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JKDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JKDokter))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlamatDokter)
                    .addComponent(AlamatDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spesialis)
                    .addComponent(SpesialisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIPDokter)
                    .addComponent(NIPDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanDokter)
                    .addComponent(tutupTambahDokter))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Panel.add(MenuTambahDokter, "card7");

        TambahPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TambahPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahPasien.setText("Tambah Pasien Inap");

        NamaPasien.setText("Nama");

        UmurPasien.setText("Umur");

        AlamatPasien.setText("Alamat");

        JKPasien.setText("Jenis kelamin");

        NoReg.setText("Nomor registrasi");

        Diagnosa.setText("Diagnosa penyakit");

        NIPDokterPasien.setText("NIP dokter pasien");

        namaPasienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPasienFieldActionPerformed(evt);
            }
        });

        JKPasienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKPasienFieldActionPerformed(evt);
            }
        });

        NIPDokterPasienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIPDokterPasienFieldActionPerformed(evt);
            }
        });

        btnSimpanPasien.setText("Simpan");
        btnSimpanPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPasienActionPerformed(evt);
            }
        });

        btnTutupTambahPasien.setText("Tutup");

        javax.swing.GroupLayout MenuTambahPasienInapLayout = new javax.swing.GroupLayout(MenuTambahPasienInap);
        MenuTambahPasienInap.setLayout(MenuTambahPasienInapLayout);
        MenuTambahPasienInapLayout.setHorizontalGroup(
            MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(Diagnosa)
                        .addGap(7, 7, 7)
                        .addComponent(diagnosaField))
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(NoReg)
                        .addGap(18, 18, 18)
                        .addComponent(noRegField))
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(JKPasien)
                        .addGap(34, 34, 34)
                        .addComponent(JKPasienField))
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UmurPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlamatPasien)
                            .addComponent(NamaPasien))
                        .addGap(62, 62, 62)
                        .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaPasienField)
                            .addComponent(alamatPasienField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(umurPasienField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(NIPDokterPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIPDokterPasienField)
                            .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(btnSimpanPasien)
                                .addGap(84, 84, 84)
                                .addComponent(btnTutupTambahPasien)
                                .addGap(115, 115, 115)))))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuTambahPasienInapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TambahPasien)
                .addGap(180, 180, 180))
        );
        MenuTambahPasienInapLayout.setVerticalGroup(
            MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TambahPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaPasien)
                    .addComponent(namaPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UmurPasien))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlamatPasien)
                    .addComponent(alamatPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JKPasien)
                    .addComponent(JKPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoReg)
                    .addComponent(noRegField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diagnosa)
                    .addComponent(diagnosaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIPDokterPasien)
                    .addComponent(NIPDokterPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPasien)
                    .addComponent(btnTutupTambahPasien))
                .addGap(45, 45, 45))
        );

        Panel.add(MenuTambahPasienInap, "card8");

        TambahRuangan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TambahRuangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahRuangan.setText("Tambah Ruangan");

        NoRuangan.setText("Masukkan nomor ruangan");

        btnSimpanRuangan.setText("Simpan");

        btnTutupTambahRuangan.setText("Tutup");

        javax.swing.GroupLayout MenuTambahRuanganLayout = new javax.swing.GroupLayout(MenuTambahRuangan);
        MenuTambahRuangan.setLayout(MenuTambahRuanganLayout);
        MenuTambahRuanganLayout.setHorizontalGroup(
            MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSimpanRuangan)
                            .addComponent(NoRuangan))
                        .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NoRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnTutupTambahRuangan))))
                    .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(TambahRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        MenuTambahRuanganLayout.setVerticalGroup(
            MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TambahRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NoRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanRuangan)
                    .addComponent(btnTutupTambahRuangan))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Panel.add(MenuTambahRuangan, "card9");

        DaftarDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DaftarDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarDokter.setText("Daftar Dokter");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout MenuViewDaftarDokterLayout = new javax.swing.GroupLayout(MenuViewDaftarDokter);
        MenuViewDaftarDokter.setLayout(MenuViewDaftarDokterLayout);
        MenuViewDaftarDokterLayout.setHorizontalGroup(
            MenuViewDaftarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuViewDaftarDokterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DaftarDokter)
                .addGap(211, 211, 211))
        );
        MenuViewDaftarDokterLayout.setVerticalGroup(
            MenuViewDaftarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DaftarDokter)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuViewDaftarDokter, "card10");

        DaftarPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DaftarPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarPasien.setText("Daftar Pasien Inap");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout MenuViewDaftarPasienInapLayout = new javax.swing.GroupLayout(MenuViewDaftarPasienInap);
        MenuViewDaftarPasienInap.setLayout(MenuViewDaftarPasienInapLayout);
        MenuViewDaftarPasienInapLayout.setHorizontalGroup(
            MenuViewDaftarPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                .addGroup(MenuViewDaftarPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(DaftarPasien))
                    .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        MenuViewDaftarPasienInapLayout.setVerticalGroup(
            MenuViewDaftarPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DaftarPasien)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Panel.add(MenuViewDaftarPasienInap, "card11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahRuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahRuanganActionPerformed

    private void hapusDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusDokterActionPerformed

    private void hapusPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusPasienActionPerformed

    private void cariPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariPasienActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void btnHapusPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusPasienActionPerformed

    private void NamaDokterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaDokterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaDokterFieldActionPerformed

    private void NIPDokterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIPDokterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIPDokterFieldActionPerformed

    private void namaPasienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPasienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPasienFieldActionPerformed

    private void JKPasienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKPasienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JKPasienFieldActionPerformed

    private void NIPDokterPasienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIPDokterPasienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIPDokterPasienFieldActionPerformed

    private void btnSimpanPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanPasienActionPerformed

    private void NoRegHapusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRegHapusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegHapusFieldActionPerformed

    private void btnTutupPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupPasienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    public JTextField getAlamatDokter() {
        return AlamatDokterField;
    }

    public void setAlamatDokter(JTextField AlamatDokter) {
        this.AlamatDokterField = AlamatDokter;
    }

    public JTextField getBidangSpesialis() {
        return SpesialisField;
    }

    public void setBidangSpesialis(JTextField BidangSpesialis) {
        this.SpesialisField = BidangSpesialis;
    }

    public JButton getCariDokter() {
        return btnCariDokter;
    }

    public void setCariDokter(JButton CariDokter) {
        this.btnCariDokter = CariDokter;
    }

    public JTextField getJenisKelaminDokter() {
        return JKDokterField;
    }

    public void setJenisKelaminDokter(JTextField JenisKelaminDokter) {
        this.JKDokterField = JenisKelaminDokter;
    }

    public JPanel getMenuCariDokter() {
        return MenuCariDokter;
    }

    public void setMenuCariDokter(JPanel MenuCariDokter) {
        this.MenuCariDokter = MenuCariDokter;
    }

    public JPanel getMenuCariPasienInap() {
        return MenuCariPasienInap;
    }

    public void setMenuCariPasienInap(JPanel MenuCariPasienInap) {
        this.MenuCariPasienInap = MenuCariPasienInap;
    }

    public JPanel getMenuHapusDokter() {
        return MenuHapusDokter;
    }

    public void setMenuHapusDokter(JPanel MenuHapusDokter) {
        this.MenuHapusDokter = MenuHapusDokter;
    }

    public JPanel getMenuHapusPasien() {
        return MenuHapusPasien;
    }

    public void setMenuHapusPasien(JPanel MenuHapusPasien) {
        this.MenuHapusPasien = MenuHapusPasien;
    }

    public JPanel getMenuTambahDokter() {
        return MenuTambahDokter;
    }

    public void setMenuTambahDokter(JPanel MenuTambahDokter) {
        this.MenuTambahDokter = MenuTambahDokter;
    }

    public JPanel getMenuTambahPasienInap() {
        return MenuTambahPasienInap;
    }

    public void setMenuTambahPasienInap(JPanel MenuTambahPasienInap) {
        this.MenuTambahPasienInap = MenuTambahPasienInap;
    }

    public JPanel getMenuTambahRuangan() {
        return MenuTambahRuangan;
    }

    public void setMenuTambahRuangan(JPanel MenuTambahRuangan) {
        this.MenuTambahRuangan = MenuTambahRuangan;
    }

    public JPanel getMenuUtama() {
        return MenuUtama;
    }

    public void setMenuUtama(JPanel MenuUtama) {
        this.MenuUtama = MenuUtama;
    }

    public JPanel getMenuViewDaftarDokter() {
        return MenuViewDaftarDokter;
    }

    public void setMenuViewDaftarDokter(JPanel MenuViewDaftarDokter) {
        this.MenuViewDaftarDokter = MenuViewDaftarDokter;
    }

    public JPanel getMenuViewDaftarPasienInap() {
        return MenuViewDaftarPasienInap;
    }

    public void setMenuViewDaftarPasienInap(JPanel MenuViewDaftarPasienInap) {
        this.MenuViewDaftarPasienInap = MenuViewDaftarPasienInap;
    }

    public JTextField getNIP() {
        return NIPField;
    }

    public void setNIP(JTextField NIP) {
        this.NIPField = NIP;
    }

    public JTextField getNIP1() {
        return NIPCariField;
    }

    public void setNIP1(JTextField NIP1) {
        this.NIPCariField = NIP1;
    }

    public JTextField getNIP2() {
        return NIPDokterField;
    }

    public void setNIP2(JTextField NIP2) {
        this.NIPDokterField = NIP2;
    }

    public JTextField getNIP3() {
        return NIPDokterPasienField;
    }

    public void setNIP3(JTextField NIP3) {
        this.NIPDokterPasienField = NIP3;
    }

    public JTextField getNamaDokter() {
        return NamaDokterField;
    }

    public void setNamaDokter(JTextField NamaDokter) {
        this.NamaDokterField = NamaDokter;
    }

    public JTextField getNoRuangan() {
        return NoRuanganField;
    }

    public void setNoRuangan(JTextField NoRuangan) {
        this.NoRuanganField = NoRuangan;
    }

    public JButton getSimpanRuangan() {
        return btnSimpanRuangan;
    }

    public void setSimpanRuangan(JButton SimpanRuangan) {
        this.btnSimpanRuangan = SimpanRuangan;
    }

    public JButton getTutupTambahRuangan() {
        return btnTutupTambahRuangan;
    }

    public void setTutupTambahRuangan(JButton TutupTambahRuangan) {
        this.btnTutupTambahRuangan = TutupTambahRuangan;
    }

    public JTextField getUmurDokter() {
        return UmurDokterField;
    }

    public void setUmurDokter(JTextField UmurDokter) {
        this.UmurDokterField = UmurDokter;
    }

    public JTextField getAlamatPasien() {
        return alamatPasienField;
    }

    public void setAlamatPasien(JTextField alamatPasien) {
        this.alamatPasienField = alamatPasien;
    }

    //public JToggleButton getCariDokter() {
    //    return cariDokter;
    //}

    public void setCariDokter(JToggleButton cariDokter) {
        this.cariDokter = cariDokter;
    }

    public JToggleButton getCariPasien() {
        return cariPasien;
    }

    public void setCariPasien(JToggleButton cariPasien) {
        this.cariPasien = cariPasien;
    }

    public JButton getCariPasienInap() {
        return btnCariPasien;
    }

    public void setCariPasienInap(JButton cariPasienInap) {
        this.btnCariPasien = cariPasienInap;
    }

    public JTextField getDiagnosa() {
        return diagnosaField;
    }

    public void setDiagnosa(JTextField diagnosa) {
        this.diagnosaField = diagnosa;
    }

    public JToggleButton getExit() {
        return exit;
    }

    public void setExit(JToggleButton exit) {
        this.exit = exit;
    }

    public JToggleButton getHapusDokter() {
        return hapusDokter;
    }

    public void setHapusDokter(JToggleButton hapusDokter) {
        this.hapusDokter = hapusDokter;
    }

    public JButton getHapusDokter1() {
        return btnHapusDokter;
    }

    public void setHapusDokter1(JButton hapusDokter1) {
        this.btnHapusDokter = hapusDokter1;
    }

    public JToggleButton getHapusPasien() {
        return hapusPasien;
    }

    public void setHapusPasien(JToggleButton hapusPasien) {
        this.hapusPasien = hapusPasien;
    }

    public JButton getHapusPasienInap() {
        return btnHapusPasien;
    }

    public void setHapusPasienInap(JButton hapusPasienInap) {
        this.btnHapusPasien = hapusPasienInap;
    }

    public JLabel getjLabel1() {
        return delDokter;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.delDokter = jLabel1;
    }

    public JLabel getjLabel10() {
        return HapusPasien;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.HapusPasien = jLabel10;
    }

    public JLabel getjLabel11() {
        return NoRegHapus;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.NoRegHapus = jLabel11;
    }

    public JLabel getjLabel12() {
        return TambahDokter;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.TambahDokter = jLabel12;
    }

    public JLabel getjLabel13() {
        return NamaDokter;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.NamaDokter = jLabel13;
    }

    public JLabel getjLabel14() {
        return UmurDokter;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.UmurDokter = jLabel14;
    }

    public JLabel getjLabel15() {
        return JKDokter;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.JKDokter = jLabel15;
    }

    public JLabel getjLabel16() {
        return AlamatDokter;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.AlamatDokter = jLabel16;
    }

    public JLabel getjLabel17() {
        return Spesialis;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.Spesialis = jLabel17;
    }

    public JLabel getjLabel18() {
        return NIPDokter;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.NIPDokter = jLabel18;
    }

    public JLabel getjLabel19() {
        return TambahPasien;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.TambahPasien = jLabel19;
    }

    public JLabel getjLabel2() {
        return NIP;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.NIP = jLabel2;
    }

    public JLabel getjLabel20() {
        return NamaPasien;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.NamaPasien = jLabel20;
    }

    public JLabel getjLabel21() {
        return UmurPasien;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.UmurPasien = jLabel21;
    }

    public JLabel getjLabel22() {
        return AlamatPasien;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.AlamatPasien = jLabel22;
    }

    public JLabel getjLabel23() {
        return JKPasien;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.JKPasien = jLabel23;
    }

    public JLabel getjLabel24() {
        return NoReg;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.NoReg = jLabel24;
    }

    public JLabel getjLabel25() {
        return Diagnosa;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.Diagnosa = jLabel25;
    }

    public JLabel getjLabel26() {
        return NIPDokterPasien;
    }

    public void setjLabel26(JLabel jLabel26) {
        this.NIPDokterPasien = jLabel26;
    }

    public JLabel getjLabel27() {
        return TambahRuangan;
    }

    public void setjLabel27(JLabel jLabel27) {
        this.TambahRuangan = jLabel27;
    }

    public JLabel getjLabel28() {
        return NoRuangan;
    }

    public void setjLabel28(JLabel jLabel28) {
        this.NoRuangan = jLabel28;
    }

    public JLabel getjLabel29() {
        return DaftarDokter;
    }

    public void setjLabel29(JLabel jLabel29) {
        this.DaftarDokter = jLabel29;
    }

    public JLabel getjLabel3() {
        return CariDokter;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.CariDokter = jLabel3;
    }

    public JLabel getjLabel30() {
        return DaftarPasien;
    }

    public void setjLabel30(JLabel jLabel30) {
        this.DaftarPasien = jLabel30;
    }

    public JLabel getjLabel4() {
        return SI;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.SI = jLabel4;
    }

    public JLabel getjLabel5() {
        return NIPCari;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.NIPCari = jLabel5;
    }

    public JLabel getjLabel6() {
        return DokterDitemukan;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.DokterDitemukan = jLabel6;
    }

    public JLabel getjLabel7() {
        return CariPasien;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.CariPasien = jLabel7;
    }

    public JLabel getjLabel8() {
        return NoRegCari;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.NoRegCari = jLabel8;
    }

    public JLabel getjLabel9() {
        return PasienDitemukan;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.PasienDitemukan = jLabel9;
    }

    public JPanel getjPanel1() {
        return Panel;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.Panel = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

    public JTable getjTable3() {
        return jTable3;
    }

    public void setjTable3(JTable jTable3) {
        this.jTable3 = jTable3;
    }

    public JTable getjTable4() {
        return jTable4;
    }

    public void setjTable4(JTable jTable4) {
        this.jTable4 = jTable4;
    }

    public JTextField getJenisKelaminPasien() {
        return JKPasienField;
    }

    public void setJenisKelaminPasien(JTextField jenisKelaminPasien) {
        this.JKPasienField = jenisKelaminPasien;
    }

    public JTextField getNamaPasien() {
        return namaPasienField;
    }

    public void setNamaPasien(JTextField namaPasien) {
        this.namaPasienField = namaPasien;
    }

    public JTextField getNomorRegistrasi() {
        return NoRegCariField;
    }

    public void setNomorRegistrasi(JTextField nomorRegistrasi) {
        this.NoRegCariField = nomorRegistrasi;
    }

    public JTextField getNomorRegistrasi1() {
        return NoRegHapusField;
    }

    public void setNomorRegistrasi1(JTextField nomorRegistrasi1) {
        this.NoRegHapusField = nomorRegistrasi1;
    }

    public JTextField getNomorRegistrasi2() {
        return noRegField;
    }

    public void setNomorRegistrasi2(JTextField nomorRegistrasi2) {
        this.noRegField = nomorRegistrasi2;
    }

    public JButton getSimpanDokter() {
        return simpanDokter;
    }

    public void setSimpanDokter(JButton simpanDokter) {
        this.simpanDokter = simpanDokter;
    }

    public JButton getSimpanPasienInap() {
        return btnSimpanPasien;
    }

    public void setSimpanPasienInap(JButton simpanPasienInap) {
        this.btnSimpanPasien = simpanPasienInap;
    }

    public JToggleButton getTambahDokter() {
        return tambahDokter;
    }

    public void setTambahDokter(JToggleButton tambahDokter) {
        this.tambahDokter = tambahDokter;
    }

    public JToggleButton getTambahPasienInap() {
        return tambahPasienInap;
    }

    public void setTambahPasienInap(JToggleButton tambahPasienInap) {
        this.tambahPasienInap = tambahPasienInap;
    }

    public JToggleButton getTambahRuangan() {
        return tambahRuangan;
    }

    public void setTambahRuangan(JToggleButton tambahRuangan) {
        this.tambahRuangan = tambahRuangan;
    }

    public JButton getTutupHapusDokter() {
        return btnTutupDokter;
    }

    public void setTutupHapusDokter(JButton tutupHapusDokter) {
        this.btnTutupDokter = tutupHapusDokter;
    }

    public JButton getTutupHapusPasienInap() {
        return btnTutupPasien;
    }

    public void setTutupHapusPasienInap(JButton tutupHapusPasienInap) {
        this.btnTutupPasien = tutupHapusPasienInap;
    }

    public JButton getTutupTambahDokter() {
        return tutupTambahDokter;
    }

    public void setTutupTambahDokter(JButton tutupTambahDokter) {
        this.tutupTambahDokter = tutupTambahDokter;
    }

    public JButton getTutupTambahPasienInap() {
        return btnTutupTambahPasien;
    }

    public void setTutupTambahPasienInap(JButton tutupTambahPasienInap) {
        this.btnTutupTambahPasien = tutupTambahPasienInap;
    }

    public JTextField getUmurPasien() {
        return umurPasienField;
    }

    public void setUmurPasien(JTextField umurPasien) {
        this.umurPasienField = umurPasien;
    }

    public JToggleButton getViewDokter() {
        return viewDokter;
    }

    public void setViewDokter(JToggleButton viewDokter) {
        this.viewDokter = viewDokter;
    }

    public JToggleButton getViewPasienInap() {
        return viewPasienInap;
    }

    public void setViewPasienInap(JToggleButton viewPasienInap) {
        this.viewPasienInap = viewPasienInap;
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    public int confimDialog(String message)
    {
        return JOptionPane.showConfirmDialog(null, message, "KONFIRMASI", JOptionPane.YES_NO_OPTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatDokter;
    private javax.swing.JTextField AlamatDokterField;
    private javax.swing.JLabel AlamatPasien;
    private javax.swing.JLabel CariDokter;
    private javax.swing.JLabel CariPasien;
    private javax.swing.JLabel DaftarDokter;
    private javax.swing.JLabel DaftarPasien;
    private javax.swing.JLabel Diagnosa;
    private javax.swing.JLabel DokterDitemukan;
    private javax.swing.JLabel HapusPasien;
    private javax.swing.JLabel JKDokter;
    private javax.swing.JTextField JKDokterField;
    private javax.swing.JLabel JKPasien;
    private javax.swing.JTextField JKPasienField;
    private javax.swing.JPanel MenuCariDokter;
    private javax.swing.JPanel MenuCariPasienInap;
    private javax.swing.JPanel MenuHapusDokter;
    private javax.swing.JPanel MenuHapusPasien;
    private javax.swing.JPanel MenuTambahDokter;
    private javax.swing.JPanel MenuTambahPasienInap;
    private javax.swing.JPanel MenuTambahRuangan;
    private javax.swing.JPanel MenuUtama;
    private javax.swing.JPanel MenuViewDaftarDokter;
    private javax.swing.JPanel MenuViewDaftarPasienInap;
    private javax.swing.JLabel NIP;
    private javax.swing.JLabel NIPCari;
    private javax.swing.JTextField NIPCariField;
    private javax.swing.JLabel NIPDokter;
    private javax.swing.JTextField NIPDokterField;
    private javax.swing.JLabel NIPDokterPasien;
    private javax.swing.JTextField NIPDokterPasienField;
    private javax.swing.JTextField NIPField;
    private javax.swing.JLabel NamaDokter;
    private javax.swing.JTextField NamaDokterField;
    private javax.swing.JLabel NamaPasien;
    private javax.swing.JLabel NoReg;
    private javax.swing.JLabel NoRegCari;
    private javax.swing.JTextField NoRegCariField;
    private javax.swing.JLabel NoRegHapus;
    private javax.swing.JTextField NoRegHapusField;
    private javax.swing.JLabel NoRuangan;
    private javax.swing.JTextField NoRuanganField;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel PasienDitemukan;
    private javax.swing.JLabel SI;
    private javax.swing.JLabel Spesialis;
    private javax.swing.JTextField SpesialisField;
    private javax.swing.JLabel TambahDokter;
    private javax.swing.JLabel TambahPasien;
    private javax.swing.JLabel TambahRuangan;
    private javax.swing.JLabel UmurDokter;
    private javax.swing.JTextField UmurDokterField;
    private javax.swing.JLabel UmurPasien;
    private javax.swing.JTextField alamatPasienField;
    private javax.swing.JButton btnCariDokter;
    private javax.swing.JButton btnCariPasien;
    private javax.swing.JButton btnHapusDokter;
    private javax.swing.JButton btnHapusPasien;
    private javax.swing.JButton btnSimpanPasien;
    private javax.swing.JButton btnSimpanRuangan;
    private javax.swing.JButton btnTutupDokter;
    private javax.swing.JButton btnTutupPasien;
    private javax.swing.JButton btnTutupTambahPasien;
    private javax.swing.JButton btnTutupTambahRuangan;
    private javax.swing.JToggleButton cariDokter;
    private javax.swing.JToggleButton cariPasien;
    private javax.swing.JLabel delDokter;
    private javax.swing.JTextField diagnosaField;
    private javax.swing.JToggleButton exit;
    private javax.swing.JToggleButton hapusDokter;
    private javax.swing.JToggleButton hapusPasien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField namaPasienField;
    private javax.swing.JTextField noRegField;
    private javax.swing.JButton simpanDokter;
    private javax.swing.JToggleButton tambahDokter;
    private javax.swing.JToggleButton tambahPasienInap;
    private javax.swing.JToggleButton tambahRuangan;
    private javax.swing.JButton tutupTambahDokter;
    private javax.swing.JTextField umurPasienField;
    private javax.swing.JToggleButton viewDokter;
    private javax.swing.JToggleButton viewPasienInap;
    // End of variables declaration//GEN-END:variables
}
