/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author aldebaranbn
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        MenuHapusDokter = new javax.swing.JPanel();
        delDokter = new javax.swing.JLabel();
        NIP = new javax.swing.JLabel();
        NIPField = new javax.swing.JTextField();
        btnHapusDokter = new javax.swing.JButton();
        btnTutupDokter = new javax.swing.JButton();
        MenuCariDokter = new javax.swing.JPanel();
        CariDokter = new javax.swing.JLabel();
        NIPCari = new javax.swing.JLabel();
        NIPCariField = new javax.swing.JTextField();
        btnCariDokter = new javax.swing.JButton();
        DokterDitemukan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        MenuCariPasienInap = new javax.swing.JPanel();
        CariPasien = new javax.swing.JLabel();
        NoRegCari = new javax.swing.JLabel();
        NoRegCariField = new javax.swing.JTextField();
        btnCariPasien = new javax.swing.JButton();
        PasienDitemukan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MenuHapusPasien = new javax.swing.JPanel();
        HapusPasien = new javax.swing.JLabel();
        NoRegHapus = new javax.swing.JLabel();
        NoRegHapusField = new javax.swing.JTextField();
        btnHapusPasien = new javax.swing.JButton();
        btnTutupPasien = new javax.swing.JButton();
        MenuTambahDokter = new javax.swing.JPanel();
        TambahDokter = new javax.swing.JLabel();
        NamaDokter = new javax.swing.JLabel();
        UmurDokter = new javax.swing.JLabel();
        JKDokter = new javax.swing.JLabel();
        AlamatDokter = new javax.swing.JLabel();
        Spesialis = new javax.swing.JLabel();
        NIPDokter = new javax.swing.JLabel();
        NamaDokterField = new javax.swing.JTextField();
        UmurDokterField = new javax.swing.JTextField();
        JKDokterField = new javax.swing.JTextField();
        AlamatDokterField = new javax.swing.JTextField();
        SpesialisField = new javax.swing.JTextField();
        NIPDokterField = new javax.swing.JTextField();
        btnSimpanDokter = new javax.swing.JButton();
        btnTutupTambahDokter = new javax.swing.JButton();
        MenuTambahPasienInap = new javax.swing.JPanel();
        TambahPasien = new javax.swing.JLabel();
        NamaPasien = new javax.swing.JLabel();
        UmurPasien = new javax.swing.JLabel();
        AlamatPasien = new javax.swing.JLabel();
        JKPasien = new javax.swing.JLabel();
        NoReg = new javax.swing.JLabel();
        Diagnosa = new javax.swing.JLabel();
        NIPDokterPasien = new javax.swing.JLabel();
        namaPasienField = new javax.swing.JTextField();
        umurPasienField = new javax.swing.JTextField();
        alamatPasienField = new javax.swing.JTextField();
        JKPasienField = new javax.swing.JTextField();
        noRegField = new javax.swing.JTextField();
        diagnosaField = new javax.swing.JTextField();
        NIPDokterPasienField = new javax.swing.JTextField();
        btnSimpanPasien = new javax.swing.JButton();
        btnTutupTambahPasien = new javax.swing.JButton();
        MenuTambahRuangan = new javax.swing.JPanel();
        TambahRuangan = new javax.swing.JLabel();
        NoRuangan = new javax.swing.JLabel();
        NoRuanganField = new javax.swing.JTextField();
        btnSimpanRuangan = new javax.swing.JButton();
        btnTutupTambahRuangan = new javax.swing.JButton();
        MenuViewDaftarDokter = new javax.swing.JPanel();
        DaftarDokter = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        MenuViewDaftarPasienInap = new javax.swing.JPanel();
        DaftarPasien = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        MenuUtama = new javax.swing.JPanel();
        mainMenu = new javax.swing.JLabel();
        btntambahRuanganMain = new javax.swing.JButton();
        btntambahDokterMain = new javax.swing.JButton();
        btntambahPasienInapMain = new javax.swing.JButton();
        btnhapusDokterMain = new javax.swing.JButton();
        btnhapusPasienMain = new javax.swing.JButton();
        btncariDokterMain = new javax.swing.JButton();
        btncariPasienMain = new javax.swing.JButton();
        btnviewPasienInapMain = new javax.swing.JButton();
        btnviewDokterMain = new javax.swing.JButton();
        btnexitMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new java.awt.CardLayout());

        delDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        delDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delDokter.setText("Hapus Dokter");

        NIP.setText("Masukkan NIP Dokter");

        btnHapusDokter.setText("Hapus");

        btnTutupDokter.setText("Tutup");

        javax.swing.GroupLayout MenuHapusDokterLayout = new javax.swing.GroupLayout(MenuHapusDokter);
        MenuHapusDokter.setLayout(MenuHapusDokterLayout);
        MenuHapusDokterLayout.setHorizontalGroup(
            MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                .addGroup(MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NIP)
                        .addGap(18, 18, 18)
                        .addComponent(NIPField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnHapusDokter)
                        .addGap(55, 55, 55)
                        .addComponent(btnTutupDokter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHapusDokterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(delDokter)
                .addGap(88, 88, 88))
        );
        MenuHapusDokterLayout.setVerticalGroup(
            MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delDokter)
                .addGap(18, 18, 18)
                .addGroup(MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIP)
                    .addComponent(NIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(MenuHapusDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusDokter)
                    .addComponent(btnTutupDokter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuHapusDokter, "card3");

        CariDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CariDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CariDokter.setText("Cari Dokter");

        NIPCari.setText("Masukkan NIP Dokter");

        btnCariDokter.setText("Cari");

        DokterDitemukan.setText("Data Dokter");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout MenuCariDokterLayout = new javax.swing.GroupLayout(MenuCariDokter);
        MenuCariDokter.setLayout(MenuCariDokterLayout);
        MenuCariDokterLayout.setHorizontalGroup(
            MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariDokterLayout.createSequentialGroup()
                .addGroup(MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCariDokterLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DokterDitemukan)
                            .addGroup(MenuCariDokterLayout.createSequentialGroup()
                                .addComponent(NIPCari)
                                .addGap(18, 18, 18)
                                .addComponent(NIPCariField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnCariDokter))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuCariDokterLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(CariDokter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuCariDokterLayout.setVerticalGroup(
            MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CariDokter)
                .addGap(18, 18, 18)
                .addGroup(MenuCariDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIPCari)
                    .addComponent(NIPCariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariDokter))
                .addGap(27, 27, 27)
                .addComponent(DokterDitemukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuCariDokter, "card4");

        CariPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CariPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CariPasien.setText("Cari Pasien Inap");

        NoRegCari.setText("Masukkan No. Registrasi Pasien");

        btnCariPasien.setText("Cari");

        PasienDitemukan.setText("Data Pasien Inap");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout MenuCariPasienInapLayout = new javax.swing.GroupLayout(MenuCariPasienInap);
        MenuCariPasienInap.setLayout(MenuCariPasienInapLayout);
        MenuCariPasienInapLayout.setHorizontalGroup(
            MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCariPasienInapLayout.createSequentialGroup()
                        .addComponent(NoRegCari)
                        .addGap(18, 18, 18)
                        .addComponent(NoRegCariField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariPasien))
                    .addComponent(PasienDitemukan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuCariPasienInapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CariPasien)
                .addGap(153, 153, 153))
        );
        MenuCariPasienInapLayout.setVerticalGroup(
            MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCariPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CariPasien)
                .addGap(18, 18, 18)
                .addGroup(MenuCariPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoRegCari)
                    .addComponent(NoRegCariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPasien))
                .addGap(18, 18, 18)
                .addComponent(PasienDitemukan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Panel.add(MenuCariPasienInap, "card5");

        HapusPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        HapusPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HapusPasien.setText("Hapus Pasien Inap");

        NoRegHapus.setText("Masukkan No. Registrasi pasien");

        NoRegHapusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRegHapusFieldActionPerformed(evt);
            }
        });

        btnHapusPasien.setText("Hapus");
        btnHapusPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPasienActionPerformed(evt);
            }
        });

        btnTutupPasien.setText("Tutup");
        btnTutupPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupPasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuHapusPasienLayout = new javax.swing.GroupLayout(MenuHapusPasien);
        MenuHapusPasien.setLayout(MenuHapusPasienLayout);
        MenuHapusPasienLayout.setHorizontalGroup(
            MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(HapusPasien))
                    .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapusPasien)
                            .addComponent(NoRegHapus))
                        .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NoRegHapusField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnTutupPasien)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        MenuHapusPasienLayout.setVerticalGroup(
            MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHapusPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HapusPasien)
                .addGap(18, 18, 18)
                .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoRegHapus)
                    .addComponent(NoRegHapusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuHapusPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusPasien)
                    .addComponent(btnTutupPasien))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Panel.add(MenuHapusPasien, "card6");

        TambahDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TambahDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahDokter.setText("Tambah Dokter");

        NamaDokter.setText("Nama");

        UmurDokter.setText("Umur");

        JKDokter.setText("Jenis kelamin");

        AlamatDokter.setText("Alamat");

        Spesialis.setText("Bidang spesialis");

        NIPDokter.setText("NIP");

        NamaDokterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaDokterFieldActionPerformed(evt);
            }
        });

        NIPDokterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIPDokterFieldActionPerformed(evt);
            }
        });

        btnSimpanDokter.setText("Simpan");

        btnTutupTambahDokter.setText("Tutup");

        javax.swing.GroupLayout MenuTambahDokterLayout = new javax.swing.GroupLayout(MenuTambahDokter);
        MenuTambahDokter.setLayout(MenuTambahDokterLayout);
        MenuTambahDokterLayout.setHorizontalGroup(
            MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UmurDokter)
                            .addComponent(NamaDokter))
                        .addGap(69, 69, 69)
                        .addComponent(NamaDokterField, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(UmurDokterField))
                            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JKDokter)
                                    .addComponent(AlamatDokter)
                                    .addComponent(Spesialis)
                                    .addComponent(NIPDokter))
                                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JKDokterField)
                                            .addComponent(AlamatDokterField)))
                                    .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SpesialisField)
                                            .addComponent(NIPDokterField))))))))
                .addGap(29, 29, 29))
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(TambahDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpanDokter)
                .addGap(72, 72, 72)
                .addComponent(btnTutupTambahDokter)
                .addGap(165, 165, 165))
        );
        MenuTambahDokterLayout.setVerticalGroup(
            MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TambahDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaDokter)
                    .addComponent(NamaDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UmurDokter)
                    .addComponent(UmurDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JKDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JKDokter))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlamatDokter)
                    .addComponent(AlamatDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spesialis)
                    .addComponent(SpesialisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIPDokter)
                    .addComponent(NIPDokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanDokter)
                    .addComponent(btnTutupTambahDokter))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Panel.add(MenuTambahDokter, "card7");

        TambahPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TambahPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahPasien.setText("Tambah Pasien Inap");

        NamaPasien.setText("Nama");

        UmurPasien.setText("Umur");

        AlamatPasien.setText("Alamat");

        JKPasien.setText("Jenis kelamin");

        NoReg.setText("Nomor registrasi");

        Diagnosa.setText("Diagnosa penyakit");

        NIPDokterPasien.setText("NIP dokter pasien");

        namaPasienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPasienFieldActionPerformed(evt);
            }
        });

        JKPasienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKPasienFieldActionPerformed(evt);
            }
        });

        NIPDokterPasienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIPDokterPasienFieldActionPerformed(evt);
            }
        });

        btnSimpanPasien.setText("Simpan");
        btnSimpanPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPasienActionPerformed(evt);
            }
        });

        btnTutupTambahPasien.setText("Tutup");

        javax.swing.GroupLayout MenuTambahPasienInapLayout = new javax.swing.GroupLayout(MenuTambahPasienInap);
        MenuTambahPasienInap.setLayout(MenuTambahPasienInapLayout);
        MenuTambahPasienInapLayout.setHorizontalGroup(
            MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(Diagnosa)
                        .addGap(7, 7, 7)
                        .addComponent(diagnosaField))
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(NoReg)
                        .addGap(18, 18, 18)
                        .addComponent(noRegField))
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(JKPasien)
                        .addGap(34, 34, 34)
                        .addComponent(JKPasienField))
                    .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                        .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UmurPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlamatPasien)
                            .addComponent(NamaPasien))
                        .addGap(62, 62, 62)
                        .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaPasienField)
                            .addComponent(alamatPasienField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(umurPasienField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuTambahPasienInapLayout.createSequentialGroup()
                        .addComponent(NIPDokterPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIPDokterPasienField)
                            .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(btnSimpanPasien)
                                .addGap(84, 84, 84)
                                .addComponent(btnTutupTambahPasien)
                                .addGap(115, 115, 115)))))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuTambahPasienInapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TambahPasien)
                .addGap(180, 180, 180))
        );
        MenuTambahPasienInapLayout.setVerticalGroup(
            MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TambahPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaPasien)
                    .addComponent(namaPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UmurPasien))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlamatPasien)
                    .addComponent(alamatPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JKPasien)
                    .addComponent(JKPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoReg)
                    .addComponent(noRegField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diagnosa)
                    .addComponent(diagnosaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIPDokterPasien)
                    .addComponent(NIPDokterPasienField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPasien)
                    .addComponent(btnTutupTambahPasien))
                .addGap(45, 45, 45))
        );

        Panel.add(MenuTambahPasienInap, "card8");

        TambahRuangan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TambahRuangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahRuangan.setText("Tambah Ruangan");

        NoRuangan.setText("Masukkan nomor ruangan");

        btnSimpanRuangan.setText("Simpan");

        btnTutupTambahRuangan.setText("Tutup");

        javax.swing.GroupLayout MenuTambahRuanganLayout = new javax.swing.GroupLayout(MenuTambahRuangan);
        MenuTambahRuangan.setLayout(MenuTambahRuanganLayout);
        MenuTambahRuanganLayout.setHorizontalGroup(
            MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSimpanRuangan)
                            .addComponent(NoRuangan))
                        .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NoRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnTutupTambahRuangan))))
                    .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(TambahRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        MenuTambahRuanganLayout.setVerticalGroup(
            MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTambahRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TambahRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NoRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuTambahRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanRuangan)
                    .addComponent(btnTutupTambahRuangan))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Panel.add(MenuTambahRuangan, "card9");

        DaftarDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DaftarDokter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarDokter.setText("Daftar Dokter");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout MenuViewDaftarDokterLayout = new javax.swing.GroupLayout(MenuViewDaftarDokter);
        MenuViewDaftarDokter.setLayout(MenuViewDaftarDokterLayout);
        MenuViewDaftarDokterLayout.setHorizontalGroup(
            MenuViewDaftarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuViewDaftarDokterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DaftarDokter)
                .addGap(211, 211, 211))
        );
        MenuViewDaftarDokterLayout.setVerticalGroup(
            MenuViewDaftarDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DaftarDokter)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuViewDaftarDokter, "card10");

        DaftarPasien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DaftarPasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaftarPasien.setText("Daftar Pasien Inap");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout MenuViewDaftarPasienInapLayout = new javax.swing.GroupLayout(MenuViewDaftarPasienInap);
        MenuViewDaftarPasienInap.setLayout(MenuViewDaftarPasienInapLayout);
        MenuViewDaftarPasienInapLayout.setHorizontalGroup(
            MenuViewDaftarPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                .addGroup(MenuViewDaftarPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(DaftarPasien))
                    .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        MenuViewDaftarPasienInapLayout.setVerticalGroup(
            MenuViewDaftarPasienInapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuViewDaftarPasienInapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DaftarPasien)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Panel.add(MenuViewDaftarPasienInap, "card11");

        mainMenu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenu.setText("Sistem Informasi Pasien Rawat Inap");

        btntambahRuanganMain.setText("Tambah Ruangan");

        btntambahDokterMain.setText("Tambah Dokter");

        btntambahPasienInapMain.setText("Tambah Pasien Inap");

        btnhapusDokterMain.setText("Hapus Dokter");

        btnhapusPasienMain.setText("Hapus Pasien");

        btncariDokterMain.setText("Cari Dokter");

        btncariPasienMain.setText("Cari Pasien");

        btnviewPasienInapMain.setText("Tampilkan Data Pasien Inap");

        btnviewDokterMain.setText("Tampilkan Data Dokter");

        btnexitMain.setText("Keluar");

        javax.swing.GroupLayout MenuUtamaLayout = new javax.swing.GroupLayout(MenuUtama);
        MenuUtama.setLayout(MenuUtamaLayout);
        MenuUtamaLayout.setHorizontalGroup(
            MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuUtamaLayout.createSequentialGroup()
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btntambahRuanganMain))
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btntambahPasienInapMain, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapusPasienMain, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncariPasienMain, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnviewPasienInapMain))
                        .addGap(60, 60, 60)
                        .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btntambahDokterMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhapusDokterMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncariDokterMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnviewDokterMain, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(MenuUtamaLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnexitMain)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuUtamaLayout.setVerticalGroup(
            MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btntambahRuanganMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambahDokterMain)
                    .addComponent(btntambahPasienInapMain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapusDokterMain)
                    .addComponent(btnhapusPasienMain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncariDokterMain)
                    .addComponent(btncariPasienMain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnviewPasienInapMain)
                    .addComponent(btnviewDokterMain))
                .addGap(18, 18, 18)
                .addComponent(btnexitMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel.add(MenuUtama, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusPasienActionPerformed

    private void NamaDokterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaDokterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaDokterFieldActionPerformed

    private void NIPDokterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIPDokterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIPDokterFieldActionPerformed

    private void namaPasienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPasienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPasienFieldActionPerformed

    private void JKPasienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKPasienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JKPasienFieldActionPerformed

    private void NIPDokterPasienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIPDokterPasienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIPDokterPasienFieldActionPerformed

    private void btnSimpanPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanPasienActionPerformed

    private void NoRegHapusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRegHapusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRegHapusFieldActionPerformed

    private void btnTutupPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupPasienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    public JLabel getAlamatDokter() {
        return AlamatDokter;
    }

    public void setAlamatDokter(JLabel AlamatDokter) {
        this.AlamatDokter = AlamatDokter;
    }

    public JTextField getAlamatDokterField() {
        return AlamatDokterField;
    }

    public void setAlamatDokterField(JTextField AlamatDokterField) {
        this.AlamatDokterField = AlamatDokterField;
    }

    public JLabel getAlamatPasien() {
        return AlamatPasien;
    }

    public void setAlamatPasien(JLabel AlamatPasien) {
        this.AlamatPasien = AlamatPasien;
    }

    public JLabel getCariDokter() {
        return CariDokter;
    }

    public void setCariDokter(JLabel CariDokter) {
        this.CariDokter = CariDokter;
    }

    public JLabel getCariPasien() {
        return CariPasien;
    }

    public void setCariPasien(JLabel CariPasien) {
        this.CariPasien = CariPasien;
    }

    public JLabel getDaftarDokter() {
        return DaftarDokter;
    }

    public void setDaftarDokter(JLabel DaftarDokter) {
        this.DaftarDokter = DaftarDokter;
    }

    public JLabel getDaftarPasien() {
        return DaftarPasien;
    }

    public void setDaftarPasien(JLabel DaftarPasien) {
        this.DaftarPasien = DaftarPasien;
    }

    public JLabel getDiagnosa() {
        return Diagnosa;
    }

    public void setDiagnosa(JLabel Diagnosa) {
        this.Diagnosa = Diagnosa;
    }

    public JLabel getDokterDitemukan() {
        return DokterDitemukan;
    }

    public void setDokterDitemukan(JLabel DokterDitemukan) {
        this.DokterDitemukan = DokterDitemukan;
    }

    public JLabel getHapusPasien() {
        return HapusPasien;
    }

    public void setHapusPasien(JLabel HapusPasien) {
        this.HapusPasien = HapusPasien;
    }

    public JLabel getJKDokter() {
        return JKDokter;
    }

    public void setJKDokter(JLabel JKDokter) {
        this.JKDokter = JKDokter;
    }

    public JTextField getJKDokterField() {
        return JKDokterField;
    }

    public void setJKDokterField(JTextField JKDokterField) {
        this.JKDokterField = JKDokterField;
    }

    public JLabel getJKPasien() {
        return JKPasien;
    }

    public void setJKPasien(JLabel JKPasien) {
        this.JKPasien = JKPasien;
    }

    public JTextField getJKPasienField() {
        return JKPasienField;
    }

    public void setJKPasienField(JTextField JKPasienField) {
        this.JKPasienField = JKPasienField;
    }

    public JPanel getMenuCariDokter() {
        return MenuCariDokter;
    }

    public void setMenuCariDokter(JPanel MenuCariDokter) {
        this.MenuCariDokter = MenuCariDokter;
    }

    public JPanel getMenuCariPasienInap() {
        return MenuCariPasienInap;
    }

    public void setMenuCariPasienInap(JPanel MenuCariPasienInap) {
        this.MenuCariPasienInap = MenuCariPasienInap;
    }

    public JPanel getMenuHapusDokter() {
        return MenuHapusDokter;
    }

    public void setMenuHapusDokter(JPanel MenuHapusDokter) {
        this.MenuHapusDokter = MenuHapusDokter;
    }

    public JPanel getMenuHapusPasien() {
        return MenuHapusPasien;
    }

    public void setMenuHapusPasien(JPanel MenuHapusPasien) {
        this.MenuHapusPasien = MenuHapusPasien;
    }

    public JPanel getMenuTambahDokter() {
        return MenuTambahDokter;
    }

    public void setMenuTambahDokter(JPanel MenuTambahDokter) {
        this.MenuTambahDokter = MenuTambahDokter;
    }

    public JPanel getMenuTambahPasienInap() {
        return MenuTambahPasienInap;
    }

    public void setMenuTambahPasienInap(JPanel MenuTambahPasienInap) {
        this.MenuTambahPasienInap = MenuTambahPasienInap;
    }

    public JPanel getMenuTambahRuangan() {
        return MenuTambahRuangan;
    }

    public void setMenuTambahRuangan(JPanel MenuTambahRuangan) {
        this.MenuTambahRuangan = MenuTambahRuangan;
    }

    public JPanel getMenuUtama() {
        return MenuUtama;
    }

    public void setMenuUtama(JPanel MenuUtama) {
        this.MenuUtama = MenuUtama;
    }

    public JPanel getMenuViewDaftarDokter() {
        return MenuViewDaftarDokter;
    }

    public void setMenuViewDaftarDokter(JPanel MenuViewDaftarDokter) {
        this.MenuViewDaftarDokter = MenuViewDaftarDokter;
    }

    public JPanel getMenuViewDaftarPasienInap() {
        return MenuViewDaftarPasienInap;
    }

    public void setMenuViewDaftarPasienInap(JPanel MenuViewDaftarPasienInap) {
        this.MenuViewDaftarPasienInap = MenuViewDaftarPasienInap;
    }

    public JLabel getNIP() {
        return NIP;
    }

    public void setNIP(JLabel NIP) {
        this.NIP = NIP;
    }

    public JLabel getNIPCari() {
        return NIPCari;
    }

    public void setNIPCari(JLabel NIPCari) {
        this.NIPCari = NIPCari;
    }

    public JTextField getNIPCariField() {
        return NIPCariField;
    }

    public void setNIPCariField(JTextField NIPCariField) {
        this.NIPCariField = NIPCariField;
    }

    public JLabel getNIPDokter() {
        return NIPDokter;
    }

    public void setNIPDokter(JLabel NIPDokter) {
        this.NIPDokter = NIPDokter;
    }

    public JTextField getNIPDokterField() {
        return NIPDokterField;
    }

    public void setNIPDokterField(JTextField NIPDokterField) {
        this.NIPDokterField = NIPDokterField;
    }

    public JLabel getNIPDokterPasien() {
        return NIPDokterPasien;
    }

    public void setNIPDokterPasien(JLabel NIPDokterPasien) {
        this.NIPDokterPasien = NIPDokterPasien;
    }

    public JTextField getNIPDokterPasienField() {
        return NIPDokterPasienField;
    }

    public void setNIPDokterPasienField(JTextField NIPDokterPasienField) {
        this.NIPDokterPasienField = NIPDokterPasienField;
    }

    public JTextField getNIPField() {
        return NIPField;
    }

    public void setNIPField(JTextField NIPField) {
        this.NIPField = NIPField;
    }

    public JLabel getNamaDokter() {
        return NamaDokter;
    }

    public void setNamaDokter(JLabel NamaDokter) {
        this.NamaDokter = NamaDokter;
    }

    public JTextField getNamaDokterField() {
        return NamaDokterField;
    }

    public void setNamaDokterField(JTextField NamaDokterField) {
        this.NamaDokterField = NamaDokterField;
    }

    public JLabel getNamaPasien() {
        return NamaPasien;
    }

    public void setNamaPasien(JLabel NamaPasien) {
        this.NamaPasien = NamaPasien;
    }

    public JLabel getNoReg() {
        return NoReg;
    }

    public void setNoReg(JLabel NoReg) {
        this.NoReg = NoReg;
    }

    public JLabel getNoRegCari() {
        return NoRegCari;
    }

    public void setNoRegCari(JLabel NoRegCari) {
        this.NoRegCari = NoRegCari;
    }

    public JTextField getNoRegCariField() {
        return NoRegCariField;
    }

    public void setNoRegCariField(JTextField NoRegCariField) {
        this.NoRegCariField = NoRegCariField;
    }

    public JLabel getNoRegHapus() {
        return NoRegHapus;
    }

    public void setNoRegHapus(JLabel NoRegHapus) {
        this.NoRegHapus = NoRegHapus;
    }

    public JTextField getNoRegHapusField() {
        return NoRegHapusField;
    }

    public void setNoRegHapusField(JTextField NoRegHapusField) {
        this.NoRegHapusField = NoRegHapusField;
    }

    public JLabel getNoRuangan() {
        return NoRuangan;
    }

    public void setNoRuangan(JLabel NoRuangan) {
        this.NoRuangan = NoRuangan;
    }

    public JTextField getNoRuanganField() {
        return NoRuanganField;
    }

    public void setNoRuanganField(JTextField NoRuanganField) {
        this.NoRuanganField = NoRuanganField;
    }

    public JPanel getPanel() {
        return Panel;
    }

    public void setPanel(JPanel Panel) {
        this.Panel = Panel;
    }

    public JLabel getPasienDitemukan() {
        return PasienDitemukan;
    }

    public void setPasienDitemukan(JLabel PasienDitemukan) {
        this.PasienDitemukan = PasienDitemukan;
    }

    public JLabel getSpesialis() {
        return Spesialis;
    }

    public void setSpesialis(JLabel Spesialis) {
        this.Spesialis = Spesialis;
    }

    public JTextField getSpesialisField() {
        return SpesialisField;
    }

    public void setSpesialisField(JTextField SpesialisField) {
        this.SpesialisField = SpesialisField;
    }

    public JLabel getTambahDokter() {
        return TambahDokter;
    }

    public void setTambahDokter(JLabel TambahDokter) {
        this.TambahDokter = TambahDokter;
    }

    public JLabel getTambahPasien() {
        return TambahPasien;
    }

    public void setTambahPasien(JLabel TambahPasien) {
        this.TambahPasien = TambahPasien;
    }

    public JLabel getTambahRuangan() {
        return TambahRuangan;
    }

    public void setTambahRuangan(JLabel TambahRuangan) {
        this.TambahRuangan = TambahRuangan;
    }

    public JLabel getUmurDokter() {
        return UmurDokter;
    }

    public void setUmurDokter(JLabel UmurDokter) {
        this.UmurDokter = UmurDokter;
    }

    public JTextField getUmurDokterField() {
        return UmurDokterField;
    }

    public void setUmurDokterField(JTextField UmurDokterField) {
        this.UmurDokterField = UmurDokterField;
    }

    public JLabel getUmurPasien() {
        return UmurPasien;
    }

    public void setUmurPasien(JLabel UmurPasien) {
        this.UmurPasien = UmurPasien;
    }

    public JTextField getAlamatPasienField() {
        return alamatPasienField;
    }

    public void setAlamatPasienField(JTextField alamatPasienField) {
        this.alamatPasienField = alamatPasienField;
    }

    public JButton getBtnCariDokter() {
        return btnCariDokter;
    }

    public void setBtnCariDokter(JButton btnCariDokter) {
        this.btnCariDokter = btnCariDokter;
    }

    public JButton getBtnCariPasien() {
        return btnCariPasien;
    }

    public void setBtnCariPasien(JButton btnCariPasien) {
        this.btnCariPasien = btnCariPasien;
    }

    public JButton getBtnHapusDokter() {
        return btnHapusDokter;
    }

    public void setBtnHapusDokter(JButton btnHapusDokter) {
        this.btnHapusDokter = btnHapusDokter;
    }

    public JButton getBtnHapusPasien() {
        return btnHapusPasien;
    }

    public void setBtnHapusPasien(JButton btnHapusPasien) {
        this.btnHapusPasien = btnHapusPasien;
    }

    public JButton getBtnSimpanDokter() {
        return btnSimpanDokter;
    }

    public void setBtnSimpanDokter(JButton btnSimpanDokter) {
        this.btnSimpanDokter = btnSimpanDokter;
    }

    public JButton getBtnSimpanPasien() {
        return btnSimpanPasien;
    }

    public void setBtnSimpanPasien(JButton btnSimpanPasien) {
        this.btnSimpanPasien = btnSimpanPasien;
    }

    public JButton getBtnSimpanRuangan() {
        return btnSimpanRuangan;
    }

    public void setBtnSimpanRuangan(JButton btnSimpanRuangan) {
        this.btnSimpanRuangan = btnSimpanRuangan;
    }

    public JButton getBtnTutupDokter() {
        return btnTutupDokter;
    }

    public void setBtnTutupDokter(JButton btnTutupDokter) {
        this.btnTutupDokter = btnTutupDokter;
    }

    public JButton getBtnTutupPasien() {
        return btnTutupPasien;
    }

    public void setBtnTutupPasien(JButton btnTutupPasien) {
        this.btnTutupPasien = btnTutupPasien;
    }

    public JButton getBtnTutupTambahDokter() {
        return btnTutupTambahDokter;
    }

    public void setBtnTutupTambahDokter(JButton btnTutupTambahDokter) {
        this.btnTutupTambahDokter = btnTutupTambahDokter;
    }

    public JButton getBtnTutupTambahPasien() {
        return btnTutupTambahPasien;
    }

    public void setBtnTutupTambahPasien(JButton btnTutupTambahPasien) {
        this.btnTutupTambahPasien = btnTutupTambahPasien;
    }

    public JButton getBtnTutupTambahRuangan() {
        return btnTutupTambahRuangan;
    }

    public void setBtnTutupTambahRuangan(JButton btnTutupTambahRuangan) {
        this.btnTutupTambahRuangan = btnTutupTambahRuangan;
    }

    public JButton getBtncariDokterMain() {
        return btncariDokterMain;
    }

    public void setBtncariDokterMain(JButton btncariDokterMain) {
        this.btncariDokterMain = btncariDokterMain;
    }

    public JButton getBtncariPasienMain() {
        return btncariPasienMain;
    }

    public void setBtncariPasienMain(JButton btncariPasienMain) {
        this.btncariPasienMain = btncariPasienMain;
    }

    public JButton getBtnexitMain() {
        return btnexitMain;
    }

    public void setBtnexitMain(JButton btnexitMain) {
        this.btnexitMain = btnexitMain;
    }

    public JButton getBtnhapusDokterMain() {
        return btnhapusDokterMain;
    }

    public void setBtnhapusDokterMain(JButton btnhapusDokterMain) {
        this.btnhapusDokterMain = btnhapusDokterMain;
    }

    public JButton getBtnhapusPasienMain() {
        return btnhapusPasienMain;
    }

    public void setBtnhapusPasienMain(JButton btnhapusPasienMain) {
        this.btnhapusPasienMain = btnhapusPasienMain;
    }

    public JButton getBtntambahDokterMain() {
        return btntambahDokterMain;
    }

    public void setBtntambahDokterMain(JButton btntambahDokterMain) {
        this.btntambahDokterMain = btntambahDokterMain;
    }

    public JButton getBtntambahPasienInapMain() {
        return btntambahPasienInapMain;
    }

    public void setBtntambahPasienInapMain(JButton btntambahPasienInapMain) {
        this.btntambahPasienInapMain = btntambahPasienInapMain;
    }

    public JButton getBtntambahRuanganMain() {
        return btntambahRuanganMain;
    }

    public void setBtntambahRuanganMain(JButton btntambahRuanganMain) {
        this.btntambahRuanganMain = btntambahRuanganMain;
    }

    public JButton getBtnviewDokterMain() {
        return btnviewDokterMain;
    }

    public void setBtnviewDokterMain(JButton btnviewDokterMain) {
        this.btnviewDokterMain = btnviewDokterMain;
    }

    public JButton getBtnviewPasienInapMain() {
        return btnviewPasienInapMain;
    }

    public void setBtnviewPasienInapMain(JButton btnviewPasienInapMain) {
        this.btnviewPasienInapMain = btnviewPasienInapMain;
    }

    public JLabel getDelDokter() {
        return delDokter;
    }

    public void setDelDokter(JLabel delDokter) {
        this.delDokter = delDokter;
    }

    public JTextField getDiagnosaField() {
        return diagnosaField;
    }

    public void setDiagnosaField(JTextField diagnosaField) {
        this.diagnosaField = diagnosaField;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

    public JTable getjTable3() {
        return jTable3;
    }

    public void setjTable3(JTable jTable3) {
        this.jTable3 = jTable3;
    }

    public JTable getjTable4() {
        return jTable4;
    }

    public void setjTable4(JTable jTable4) {
        this.jTable4 = jTable4;
    }

    public JLabel getMainMenu() {
        return mainMenu;
    }

    public void setMainMenu(JLabel mainMenu) {
        this.mainMenu = mainMenu;
    }

    public JTextField getNamaPasienField() {
        return namaPasienField;
    }

    public void setNamaPasienField(JTextField namaPasienField) {
        this.namaPasienField = namaPasienField;
    }

    public JTextField getNoRegField() {
        return noRegField;
    }

    public void setNoRegField(JTextField noRegField) {
        this.noRegField = noRegField;
    }

    public JTextField getUmurPasienField() {
        return umurPasienField;
    }

    public void setUmurPasienField(JTextField umurPasienField) {
        this.umurPasienField = umurPasienField;
    }

    
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
    public int confimDialog(String message)
    {
        return JOptionPane.showConfirmDialog(null, message, "KONFIRMASI", JOptionPane.YES_NO_OPTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatDokter;
    private javax.swing.JTextField AlamatDokterField;
    private javax.swing.JLabel AlamatPasien;
    private javax.swing.JLabel CariDokter;
    private javax.swing.JLabel CariPasien;
    private javax.swing.JLabel DaftarDokter;
    private javax.swing.JLabel DaftarPasien;
    private javax.swing.JLabel Diagnosa;
    private javax.swing.JLabel DokterDitemukan;
    private javax.swing.JLabel HapusPasien;
    private javax.swing.JLabel JKDokter;
    private javax.swing.JTextField JKDokterField;
    private javax.swing.JLabel JKPasien;
    private javax.swing.JTextField JKPasienField;
    private javax.swing.JPanel MenuCariDokter;
    private javax.swing.JPanel MenuCariPasienInap;
    private javax.swing.JPanel MenuHapusDokter;
    private javax.swing.JPanel MenuHapusPasien;
    private javax.swing.JPanel MenuTambahDokter;
    private javax.swing.JPanel MenuTambahPasienInap;
    private javax.swing.JPanel MenuTambahRuangan;
    private javax.swing.JPanel MenuUtama;
    private javax.swing.JPanel MenuViewDaftarDokter;
    private javax.swing.JPanel MenuViewDaftarPasienInap;
    private javax.swing.JLabel NIP;
    private javax.swing.JLabel NIPCari;
    private javax.swing.JTextField NIPCariField;
    private javax.swing.JLabel NIPDokter;
    private javax.swing.JTextField NIPDokterField;
    private javax.swing.JLabel NIPDokterPasien;
    private javax.swing.JTextField NIPDokterPasienField;
    private javax.swing.JTextField NIPField;
    private javax.swing.JLabel NamaDokter;
    private javax.swing.JTextField NamaDokterField;
    private javax.swing.JLabel NamaPasien;
    private javax.swing.JLabel NoReg;
    private javax.swing.JLabel NoRegCari;
    private javax.swing.JTextField NoRegCariField;
    private javax.swing.JLabel NoRegHapus;
    private javax.swing.JTextField NoRegHapusField;
    private javax.swing.JLabel NoRuangan;
    private javax.swing.JTextField NoRuanganField;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel PasienDitemukan;
    private javax.swing.JLabel Spesialis;
    private javax.swing.JTextField SpesialisField;
    private javax.swing.JLabel TambahDokter;
    private javax.swing.JLabel TambahPasien;
    private javax.swing.JLabel TambahRuangan;
    private javax.swing.JLabel UmurDokter;
    private javax.swing.JTextField UmurDokterField;
    private javax.swing.JLabel UmurPasien;
    private javax.swing.JTextField alamatPasienField;
    private javax.swing.JButton btnCariDokter;
    private javax.swing.JButton btnCariPasien;
    private javax.swing.JButton btnHapusDokter;
    private javax.swing.JButton btnHapusPasien;
    private javax.swing.JButton btnSimpanDokter;
    private javax.swing.JButton btnSimpanPasien;
    private javax.swing.JButton btnSimpanRuangan;
    private javax.swing.JButton btnTutupDokter;
    private javax.swing.JButton btnTutupPasien;
    private javax.swing.JButton btnTutupTambahDokter;
    private javax.swing.JButton btnTutupTambahPasien;
    private javax.swing.JButton btnTutupTambahRuangan;
    private javax.swing.JButton btncariDokterMain;
    private javax.swing.JButton btncariPasienMain;
    private javax.swing.JButton btnexitMain;
    private javax.swing.JButton btnhapusDokterMain;
    private javax.swing.JButton btnhapusPasienMain;
    private javax.swing.JButton btntambahDokterMain;
    private javax.swing.JButton btntambahPasienInapMain;
    private javax.swing.JButton btntambahRuanganMain;
    private javax.swing.JButton btnviewDokterMain;
    private javax.swing.JButton btnviewPasienInapMain;
    private javax.swing.JLabel delDokter;
    private javax.swing.JTextField diagnosaField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel mainMenu;
    private javax.swing.JTextField namaPasienField;
    private javax.swing.JTextField noRegField;
    private javax.swing.JTextField umurPasienField;
    // End of variables declaration//GEN-END:variables
}
